### ISSUE TITLE
CurrentContext is null

### ISSUE THREAD

**Issue by VinnieThePooh** [VinnieThePooh/Edison.TickTackToe#2]
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.HttpContextExtensions.GetOwinEnvironment(HttpContext context)
   at System.Web.HttpContextExtensions.GetOwinContext(HttpContext context)
   at Edison.TickTackToe.Web.GamesHub.<GetUserByName>d__9.MoveNext() in H:\EDUCATION\My projects\VSDefaultFolder\VS2015\Edison.TickTackToe\Edison.TickTackToe.Web\GamesHub.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Edison.TickTackToe.Web.GamesHub.<AcceptInvitation>d__4.MoveNext() in H:\EDUCATION\My projects\VSDefaultFolder\VS2015\Edison.TickTackToe\Edison.TickTackToe.Web\GamesHub.cs:line 90

**Comment by VinnieThePooh** [comment]
Finally fixed in this commit 225a38f3cf8559d220145e856f5c1fcc0b11e1d6
